### ISSUE TITLE
ML benötigt für den erneuten Lerndurchgang ein "All Sessions closed"-Event

### ISSUE THREAD

**Issue by DimadonDL** [Purii/hdm-wim-devlab#12]
Das Event sollte letztendlich nur sagen, dass alle Sessions beendet sind. Inhaltlich müssen keine besonderen Attribute beigefügt werden.

**Comment by WendelinHerrmann** [comment]
Ich denke dadurch, dass der Überblick über die Sessions bei CEP liegt und wir hier eigentlich keine Beteiligung haben, müsste das komplett zwischen CEP und ML machbar sein :)
