### ISSUE TITLE
[Alle] Topics definieren

### ISSUE THREAD

**Issue by Purii** [Purii/hdm-wim-devlab#14]
Wir sollten gemeinsam entscheiden, welche Topics benötigen. Topics sind unsere Kommunikationskanäle über die später Events ausgetauscht werden.

**Beispiele:**

* FeedbackGui
* Insights
* Offers
....

Die aktuelle Liste könnt Ihr in der [README.md](https://github.com/Purii/hdm-wim-devlab/blob/master/README.md#topics) nachlesen.

**Comment by nilsbch** [comment]
- Token

**Comment by itsBen** [comment]
#32
