### ISSUE TITLE
Alle -> PubSub

### ISSUE THREAD

**Issue by itsBen** [Purii/hdm-wim-devlab#19]
Schreibt mal bitte alle auf, was ihr uns schickt.

**Comment by nilsbch** [comment]
Konkret meinen wir also: 
Wie genau ist eure PubSubMessage für einen bestimmten Fall (Feedback, Offer, etc. EVENT_TYPE) aufgebaut? Welcher Inhalt ist in data, welcher in Attributes?

**Comment by DimadonDL** [comment]
Also im Fall von ML sieht der Response derzeit so aus:

Message ID            User ID             DocumentID            Dokumenten_Nutzungsassoziation
151651                   156165             151651651               true

Entweder alles in der Nachricht oder jeweils ein Attribut. Das muss noch abgeklärt werden.
