### ISSUE TITLE
Gui -> SemRep (neue Usereinträge)

### ISSUE THREAD

**Issue by mateos-alliaj** [Purii/hdm-wim-devlab#23]
# UserInformationEvent 
SemRep stell für Gui eine Abfrage-Methode bereit. 
Eingabeparameter: 
```
userID 
```
### 1.) User bereits in Ontologie: 
Rückgabe:
```
UserID=, Vorname=Lisa, Nachname=, 
Mail=, Projekt=, Projektrolle=, Abteilung=
```
*UserID=, Vorname=Lisa, Nachname=, Mail= -> von Google Credential
**Projekt=, Projektrolle=, Abteilung= -> Formular

### 2.) User muss neu in die Ontologie eingetragen werden:
a) User nicht in Ontologie:
Rückgabe:
```
UserID=userID, Vorname=null, Nachname=null, 
Mail=null, Projekt=null, Projektrolle=null, Abteilung=null
```
b) neu anlegen in Ontologie:
Rückgabe:
```
UserID=, Vorname=Lisa, Nachname=, 
Mail=, Projekt=, Projektrolle=, Abteilung=

```

**Comment by Mag91** [comment]
hi, 

wie kurz besprochen bräuchten wir eine getter methode/ Event für die punkte Projekt=, Projektrolle=, Abteilung=. 
Die Methode soll alles zurückgeben, dass es in der Ontologie gibt. Wir fügen es dann in ein Dropdown ein und der User kann jeweils einen Eintrag auswählen: 

(muss man noch hübsch machen)
![grafik](https://user-images.githubusercontent.com/23134406/27261290-a14a64a0-5440-11e7-9bac-ed1109a91bca.png)

**Comment by mateos-alliaj** [comment]
@Mag91 
Servus Markus, ich trage die ganzen Events von uns dann in das Issue '[SEMANTIC REPR] Attribute aller Events festlegen #27' mit der Event-Gruppe ein. Das doppelte Eintragen von Issues ist zu aufwändid.
