### ISSUE TITLE
Dokumentation aufräumen und aufbauen

### ISSUE THREAD

**Issue by Purii** [Purii/hdm-wim-devlab#25]
- [x] README.md aufräumen
- [x] `/docs` aufbauen
- [x] `/docs` Synchron mit tatsächlicher Implementierung von SharedLibs

**Comment by itsBen** [comment]
- [x] ggfs. Topic aus den Klassen in  `Events.md` entfernen @Purii ?
- [x] Anleitung zur Installation des Google Cloud SDK und einsatz der gcloud console @ChristianSchn 
- [x] Anleitung zur Einbindung der SharedLib
