### ISSUE TITLE
Events: SemRep

### ISSUE THREAD

**Issue by ChristianSchn** [Purii/hdm-wim-devlab#27]
# Hallo Semantic Representation

bitte ergänzt für alle aufgeführten Events die Attribute durch Edit. Die Schreibweise ist erstmal unwichtig, wir normieren die Attribute in der [Konstantenklasse](https://github.com/Purii/hdm-wim-devlab/blob/master/SharedLib/src/main/java/de/hdm/wim/sharedLib/Constants.java).  Falls Events fehlen, bitte um direkte Rückmeldung. Eine Liste aller Events inkl. Aufbau ist [hier](https://github.com/Purii/hdm-wim-devlab/blob/master/docs/Events.md) einzusehen.

## DepartmentInformationEvent
*erstellt durch SR; Detailinformationen über die Abteilung; published in Topic: <code>Constants.PubSub.Topic.INFORMATION</code>*
#### Attribute (siehe Kommentar)
<ul><li><code>sessionId: String</code></li><li><code>tokenId: String</code></li><li><code>...</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SEMANTIC_REPRESENTATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.DEPARTMENT_INFO</code></li></ul>

## DocumentInformationEvent
*erstellt durch SR; Detailinformationen zu den gefundenen Dokumenten; published in Topic: <code>Constants.PubSub.Topic.INFORMATION</code>*
#### Attribute (siehe Kommentar)
<ul><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SEMANTIC_REPRESENTATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.DOCUMENT_INFO</code></li></ul>

## OfferEvent
*erstellt durch SR; Dokumentenvorschläge zur Anzeige; published in Topic: <code>Constants.PubSub.Topic.OFFERS</code>*
#### Attribute
<ul><li><code>userId: String</code></li><li><code>documentId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SEMANTIC_REPRESENTATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.OFFER</code></li></ul>

## UserInformationEvent
*erstellt durch SR; Detailinformationen über den User, wird bspw. beim Login ausgelöst; published in Topic: <code>Constants.PubSub.Topic.INFORMATION</code>*
#### Attribute (siehe Kommentar)
<ul><li><code>sessionId: String</code></li><li><code>tokenId: String</code></li><li><code>...</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SEMANTIC_REPRESENTATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.USER_INFO</code></li></ul>

## UserNonExistentEvent
*erstellt durch SR; ein User ist noch nicht in der Datenbank vorhanden, Event für die GUI zur Abfrage der Daten; published in Topic: <code>Constants.PubSub.Topic.INFORMATION</code>*
#### Attribute
<ul><li><code>sessionId: String</code></li><li><code>...</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SEMANTIC_REPRESENTATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.USER_INFO</code></li></ul>

## ProjectInformationEvent
*erstellt durch SR; Detailinformationen über die Projekte; published in Topic: <code>Constants.PubSub.Topic.INFORMATION</code>*
#### Attribute (siehe Kommentar)
<ul><li><code>sessionId: String</code></li><li><code>tokenId: String</code></li><li><code>...</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SEMANTIC_REPRESENTATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.PROJECT_INFO</code></li></ul>

**Comment by WendelinHerrmann** [comment]
Mir fehlt hier wie im GUI-Issue teilweise schon erwähnt 
- zum einen das Event, dass aussagt, dass ein User neu ist (GUI braucht das, damit wir die Informationen abfragen können) 
- ist das DocumentInformationEvent die besprochene Initialisierung mit allen für das Gespräch möglichen Dokumenten? falls nein fehlt dieses Event
- Vorschläge werden von uns wie abgesprochen in der Form erwartet, dass nicht einfach ein Dokument gepushed wird (wie es aktuell im OfferEvent der Fall ist wenn ich das richtig lese), sondern Updates kommen welche Dokumente neu relevant sind und welche nicht länger relevant sind. ohne "nicht mehr relevant" macht jegliche Visualisierung keinen Sinn!

**Comment by mateos-alliaj** [comment]
# **UserInformationEvent**
**Bsp.:**
`SessionID=793dnj; TokenID=a5ad7379-e0e1-4e02-83be-1f4cb73b25e4; Person={UserID=6, Vorname=Lisa, Nachname=Meier, Mail=lisa.meier@brokenbits.com, Projekt=HighNet, Projektrolle=Projektmitarbeiter, Abteilung=IT, DokAutor=KickOff-HighNet, DokAufrufe=KickOff-HighNet, DokFavorit=KickOff-HighNet}`

**Struktur & Attribute**
```
SessionID=; 
TokenID=; 
UserID=, Vorname=, Nachname=, Mail=, Projekt=, 
Projektrolle=, Abteilung=, DokAutor=, DokAufrufe=, DokFavorit=
```

**Comment by mateos-alliaj** [comment]
# **DocumentInformationEvent**
**Bsp.:**
`SessionID=1; TokenID=eec5b4d1-9101-44da-8e50-6b993e0c7bb5; DokID=1mC30R185Km9Y9HoE2uUgVDJi41IXKelPJEBhBeXH2PY, DokName=Aufgabenliste, DokURL=https://docs.google.com/document/d/1mC30R185Km9Y9HoE2uUgVDJi41IXKelPJEBhBeXH2PY/edit, DokErstelldatum=2017-04-22T11:33:00, DokVersion=1.1, DokTyp=Google Docs, DokumentVerfasstVonPerson=Kristjan_Alliaj, DokumentGehoertZuProjekt=HighNet, DokumentFavorisiertVonPerson=Björn_Zimmermann, DokKeywords=milestone, tasks, DokOrdner=Testdokumente-HighNet`

**Struktur & Attribute**
```
SessionID=; 
TimeStamp=; 
DokID=, DokName=, DokURL=, DokErstelldatum=, 
DokVersion=, DokTyp=, DokumentVerfasstVonPerson=, 
DokumentGehoertZuProjekt=, DokumentFavorisiertVonPerson=, 
DokKeywords=, DokOrdner=
```

**Comment by mateos-alliaj** [comment]
# **ProjectInformationEvent**
**Bsp.:**
`SessionID=1; TokenID=eec5b4d1-9101-44da-8e50-6b993e0c7bb5; ProjektID=1, ProjektName=HighNet, ProjektGehoertZuUnternehmen=Star_Cars, ProjektGehoertZuAbteilung=Research_and_Development, ProjektHatProjektmitglied=Mateos_Alliaj, ProjektHatDokument=Meilensteine-HighNet`

**Struktur & Attribute**
```
SessionID=; 
TokenID=; 
ProjektID=, ProjektName=, ProjektGehoertZuUnternehmen=,
ProjektGehoertZuAbteilung=, 
ProjektHatProjektmitglied=, ProjektHatDokument=
```

**Comment by mateos-alliaj** [comment]
# **DepartmentInformationEvent**
**Bsp.:**
`SessionID=1; TokenID=eec5b4d1-9101-44da-8e50-6b993e0c7bb5; AbteilungID=2, AbteilungName=IT, AbteilungKuerzel=IT, AbteilungHatProjekt=HighNet, Big_Data_Diagnosis, AbteilungHatMitarbeiter=Mateos_Alliaj, Björn_Zimmermann, Kristjan_Alliaj, Lisa_Meier, Ivan_Kurtovic, AbteilungGehoertZuUnternehmen=Broken_Bits`

**Struktur & Attribute**
```
SessionID=; 
TimeStamp=; 
AbteilungID=, AbteilungName=, AbteilungKuerzel=, 
AbteilungHatProjekt=,, AbteilungHatMitarbeiter=, 
AbteilungGehoertZuUnternehmen=
```

**Comment by mateos-alliaj** [comment]
@WendelinHerrmann
Mir fehlt hier wie im GUI-Issue teilweise schon erwähnt
- zum einen das Event, dass aussagt, dass ein User neu ist (GUI braucht das, damit wir die Informationen abfragen können) 
`Das ist mit euch so geklärt, dass ihr alle User über ihre UserID bei uns auf der Ontologie abfragen könnt. Wenn es den User bei uns nicht gibt, registriert ihr den neu, woraufhin er bei uns neu angelegt wird.`
- ist das DocumentInformationEvent die besprochene Initialisierung mit allen für das Gespräch möglichen Dokumenten? falls nein fehlt dieses Event
`Ne, das 'DocumentInformationEvent' ist nur für EVENT, damit sie den Kontext ermitteln können. Für eure Initialisierung gibt es bei uns schon eine Methode Wendelin.`
- Vorschläge werden von uns wie abgesprochen in der Form erwartet, dass nicht einfach ein Dokument gepushed wird (wie es aktuell im OfferEvent der Fall ist wenn ich das richtig lese), sondern Updates kommen welche Dokumente neu relevant sind und welche nicht länger relevant sind. ohne "nicht mehr relevant" macht jegliche Visualisierung keinen Sinn!
`Ja, ist auch so schon umgesetzt. Relevant = 1 , irrelevant = 0...schau mal in den SemRep -> Gui Issue.`

**Comment by WendelinHerrmann** [comment]
@mateos-alliaj 

bin auch davon ausgegangen, dass sich an unseren Absprachen nichts geänder hat, wollte nur darlegen, dass in der Festlegung der Events als Grundlage für das Gesamtsystem das so noch nicht passt.

- bezüglich dem User, wir schicken euch die UserID und ihr sucht, wir brauchen aber auch für den Fall, dass ihr ihn nicht kennt eine entsprechende Rückmeldung, weil wir sonst gar nicht die neuen Infos abfragen würden
- Okay gut, dann brauchen wir aber trotzdem das Event für die Methode, sonst bekommen wir das ja nicht mit von euch, sind ja nur über den Channel verbunden
- dann muss aber eben das spezifizierte Vorschlagsevent auch so aussehen, das Spezifizieren von Events hier mit Attributen macht ja nur Sinn, wenn's zu den restlichen Abmachungen und Methoden passt und sich am Ende alle dran halten

**Comment by ChristianSchn** [comment]
@mateos-alliaj 

Habe die Events hinzugefügt, kannst du bitte für UserNonExistent Attribute ergänzen? Welche Events braucht ihr noch für den initialen Vorschlag aller geeigneten Dokumente? Wie sieht euer OfferEvent aus, arbeitet mal bitte Wende's Anforderungen ein.

**Comment by mateos-alliaj** [comment]
@ChristianSchn

**- Habe die Events hinzugefügt, kannst du bitte für UserNonExistent Attribute ergänzen?**
Dazu gibt es bereits ein Issue, siehe 'Gui -> SemRep (neue Usereinträge) #23':
2.) User muss neu in die Ontologie eingetragen werden:
a) User nicht in Ontologie:
Rückgabe:
```
UserID=userID, Vorname=null, Nachname=null, 
Mail=null, Projekt=null, Projektrolle=null, Abteilung=null
```

**- Welche Events braucht ihr noch für den initialen Vorschlag aller geeigneten Dokumente?**
### InformationToAllDocumentsEvent
```
Dokumentvorschlag(0-n), SessionID='', 
TimeStamp='YYYY-MM-DD hh:mm:ss.ms', 
DokID='', DokName='', DokPrio=1, DokTyp='', DokURL='', DokOrdner=''
```

**- Wie sieht euer OfferEvent aus, arbeitet mal bitte Wende's Anforderungen ein.**
Die Punkte wurden bereits nach einem klärenden Sykpe-Gespräch eingearbeitet.

**Comment by mateos-alliaj** [comment]
# InformationToAllDocumentsEvent
**Bsp.:**
`Dokument0: SessionID=1, TimeStamp=2017-06-18 17:32:37.594, DokID=1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM, DokName=Projektplanung, DokPrio=0, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM/edit, DokOrdner=Testdokumente-HighNet, `

**Struktur & Attribute**
```
Dokument(0-n), SessionID='', 
TimeStamp='YYYY-MM-DD hh:mm:ss.ms', 
DokID='', DokName='', DokPrio=1, DokTyp='', DokURL='', DokOrdner=''
```

**Comment by mateos-alliaj** [comment]
# OfferEvent
**Bsp.:**
```
Dokument0: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM, DokName=Projektplanung, DokPrio=0, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM/edit, DokOrdner=Testdokumente-HighNet, 
Dokument1: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1jQFZmcS__-CtScjqd3g5KKM8xepPnMSqaepy2ag2jNc, DokName=Meilensteine, DokPrio=0, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1jQFZmcS__-CtScjqd3g5KKM8xepPnMSqaepy2ag2jNc/edit, DokOrdner=Testdokumente-HighNet, 
Dokument2: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1SAI8Y7j6kNfbbdYVaUpEPipzy-WhcvmuPRynSg76UIM, DokName=Kostenplanung, DokPrio=0, DokTyp=Google Tabellen, DokURL=https://docs.google.com/spreadsheets/d/1SAI8Y7j6kNfbbdYVaUpEPipzy-WhcvmuPRynSg76UIM/edit, DokOrdner=Testdokumente-HighNet, 
Dokument3: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1jYsTPJH8gaIiATix9x34Ekcj31ifJMkPNb0RmxnuGxs, DokName=Kostenaufstellung, DokPrio=0, DokTyp=Google Tabellen, DokURL=https://docs.google.com/spreadsheets/d/1jYsTPJH8gaIiATix9x34Ekcj31ifJMkPNb0RmxnuGxs/edit, DokOrdner=Testdokumente-HighNet, 
Dokument4: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1kapEE9ui6oYu-uUZF6qjg-j85iJz_w7lNmtyLHZA7lc, DokName=KickOff, DokPrio=0, DokTyp=Google Präsentationen, DokURL=https://docs.google.com/presentation/d/1kapEE9ui6oYu-uUZF6qjg-j85iJz_w7lNmtyLHZA7lc/edit, DokOrdner=Testdokumente-HighNet, 
Dokument5: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1Ktol-SWvAh8pnHG2O7HdPrfbEVZWX3Vf2YIPYXA_8gI, DokName=Finanzreport, DokPrio=0, DokTyp=Google Präsentationen, DokURL=https://docs.google.com/presentation/d/1Ktol-SWvAh8pnHG2O7HdPrfbEVZWX3Vf2YIPYXA_8gI/edit, DokOrdner=Testdokumente-BlackWater, 
Dokument6: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1mC30R185Km9Y9HoE2uUgVDJi41IXKelPJEBhBeXH2PY, DokName=Aufgabenliste, DokPrio=0, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1mC30R185Km9Y9HoE2uUgVDJi41IXKelPJEBhBeXH2PY/edit, DokOrdner=Testdokumente-HighNet, 
Dokument7: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1Cl1k0OYjdubR0_BqiFp2xaRGeRpqqUz8pucX7iQwIQ8, DokName=Anforderungen, DokPrio=0, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1Cl1k0OYjdubR0_BqiFp2xaRGeRpqqUz8pucX7iQwIQ8/edit, DokOrdner=Testdokumente-Big_Data_Diagnosis, 
Favorit0: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM, DokName=Projektplanung, DokPrio=1, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM/edit, DokOrdner=Testdokumente-HighNet, 
Favorit1: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1SAI8Y7j6kNfbbdYVaUpEPipzy-WhcvmuPRynSg76UIM, DokName=Kostenplanung, DokPrio=1, DokTyp=Google Tabellen, DokURL=https://docs.google.com/spreadsheets/d/1SAI8Y7j6kNfbbdYVaUpEPipzy-WhcvmuPRynSg76UIM/edit, DokOrdner=Testdokumente-HighNet, 
Favorit2: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1kapEE9ui6oYu-uUZF6qjg-j85iJz_w7lNmtyLHZA7lc, DokName=KickOff, DokPrio=1, DokTyp=Google Präsentationen, DokURL=https://docs.google.com/presentation/d/1kapEE9ui6oYu-uUZF6qjg-j85iJz_w7lNmtyLHZA7lc/edit, DokOrdner=Testdokumente-HighNet, 
Dokumentvorschlag0: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM, DokName=Projektplanung, DokPrio=1, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1gnH6sv3VqGEveSSf0SoS7dJqWaUyUnZm6-QrdiH7vCM/edit, DokOrdner=Testdokumente-HighNet, 
Dokumentvorschlag1: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1jQFZmcS__-CtScjqd3g5KKM8xepPnMSqaepy2ag2jNc, DokName=Meilensteine, DokPrio=1, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1jQFZmcS__-CtScjqd3g5KKM8xepPnMSqaepy2ag2jNc/edit, DokOrdner=Testdokumente-HighNet, 
Dokumentvorschlag2: SessionID=1, TimeStamp=2017-06-18 17:23:26.344, DokID=1mC30R185Km9Y9HoE2uUgVDJi41IXKelPJEBhBeXH2PY, DokName=Aufgabenliste, DokPrio=1, DokTyp=Google Docs, DokURL=https://docs.google.com/document/d/1mC30R185Km9Y9HoE2uUgVDJi41IXKelPJEBhBeXH2PY/edit, DokOrdner=Testdokumente-HighNet, 
```

**Struktur & Attribute**
```
Dokument(0-n), SessionID='', 
TimeStamp='YYYY-MM-DD hh:mm:ss.ms', 
DokID='', DokName='', DokPrio=1, DokTyp='', DokURL='', DokOrdner='',

Favorit(0-n), SessionID='', 
TimeStamp='YYYY-MM-DD hh:mm:ss.ms', 
DokID='', DokName='', DokPrio=1, DokTyp='', DokURL='', DokOrdner='',

Dokumentvorschlag(0-n), SessionID='', 
TimeStamp='YYYY-MM-DD hh:mm:ss.ms', 
DokID='', DokName='', DokPrio=1, DokTyp='', DokURL='', DokOrdner='',
```

**Comment by mateos-alliaj** [comment]
@ChristianSchn
@WendelinHerrmann 
Kann man die Fragen von uns, wenn die bisherigen Punkte geklärt sind, nun löschen, damit es etwas übersichtlicher wird?

**Comment by mateos-alliaj** [comment]
@ChristianSchn
Ahja ich habe gerade gesehen, dass du ein 'UserNonExistentEvent' aufführst. Das haben wir nicht, denn wir geben dann einfach das folgende zurück:
```
UserID=userID, Vorname=null, Nachname=null, 
Mail=null, Projekt=null, Projektrolle=null, Abteilung=null
```
Ist also im Rahmen des UserInformationEvent

**Comment by mateos-alliaj** [comment]
# AllProjectsEvent
**Bsp.:**
`SessionID=1; ProjektName=HighNet, ProjektName=Big_Data_Diagnosis, ProjektName=BlackWater`

**Struktur & Attribute**
```
SessionID=; 
ProjektName=, 
```

**Comment by mateos-alliaj** [comment]
# AllProjectRolesEvent
**Bsp.:**
`SessionID=1; ProjektRolle=Entwickler, ProjektRolle=Projektleiter, ProjektRolle=Projektmitarbeiter`

**Struktur & Attribute**
```
SessionID=; 
ProjektRolle=, 
```

**Comment by mateos-alliaj** [comment]
# AllDepartmentsEvent
**Bsp.:**
`SessionID=1; AbteilungName=IT, AbteilungName=Finance, AbteilungName=Research_and_Development`

**Struktur & Attribute**
```
SessionID=; 
AbteilungName=,
```

**Comment by ChristianSchn** [comment]
@mateos-alliaj 
Ich schreib allgemein alle Attribute in Englisch, brauchst jetz nix ändern, nur dass du es weißt.
Ihr müsst ja nur die Klasse letztlich mit Values befüllen

**Comment by WendelinHerrmann** [comment]
@ChristianSchn  und @mateos-alliaj 

wie gerade mit Mateos telefonisch besprochen fehlt noch ein AllCompaniesEvent analog zu den anderen All...Events :) 
Events dienen dazu, dass GUI in der Abfrage die Dropdowns mit Auswahlmöglichkeiten befüllen kann

**Comment by ChristianSchn** [comment]
Wird erledigt
