### ISSUE TITLE
[GUI] Attribute aller Events festlegen

### ISSUE THREAD

**Issue by ChristianSchn** [Purii/hdm-wim-devlab#28]
# Hallo GUI

bitte ergänzt für alle aufgeführten Events die Attribute durch Edit. Die Schreibweise ist erstmal unwichtig, wir normieren die Attribute in der [Konstantenklasse](https://github.com/Purii/hdm-wim-devlab/blob/master/SharedLib/src/main/java/de/hdm/wim/sharedLib/Constants.java).  Falls Events fehlen, bitte um direkte Rückmeldung. Eine Liste aller Events inkl. Aufbau ist [hier](https://github.com/Purii/hdm-wim-devlab/blob/master/docs/Events.md) einzusehen.

## UserLoginEvent
*erstellt durch GUI; ein User hat sich eingeloggt; published in Topic: <code>Constants.PubSub.Topic.SESSIONINSIGHTS</code>*
#### Attribute
<ul><li><code>userId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.USER_LOGIN</code></li></ul>

## SessionStartEvent
*erstellt durch GUI; ein User startet eine neue Session; published in Topic: <code>Constants.PubSub.Topic.SESSIONINSIGHTS</code>*
#### Attribute
<ul><li><code>sessionId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.SESSION_START</code></li></ul>

## UserJoinedSessionEvent
*erstellt durch GUI; ein User hat sich an einer Session angemeldet; published in Topic: <code>Constants.PubSub.Topic.SESSIONINSIGHTS</code>*
<ul><li><code>userId: String</code></li><li><code>sessionId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.USER_JOINED_SESSION</code></li></ul> 

## UserStartEvent
*erstellt durch GUI; ein User startet die Vorschlagsfunktion; published in Topic: <code>Constants.PubSub.Topic.SESSIONINSIGHTS</code>*
<ul><li><code>userId: String</code></li><li><code>sessionId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.USER_START</code></li></ul> 

#### Attribute
*erstellt durch GUI; Ping-Event zur Aktivitätsprüfung; published in Topic: <code>Constants.PubSub.Topic.SESSIONINSIGHTS</code>*
<ul><li><code>userId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.STAYALIVE</code></li></ul>

## UserLeftSessionEvent
*erstellt durch GUI; ein User hat sich von einer Session abgemeldet; published in Topic: <code>Constants.PubSub.Topic.SESSIONINSIGHTS</code>*
<ul><li><code>userId: String</code></li><li><code>sessionId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.USER_LEFT_SESSION</code></li></ul> 

## FeedbackEvent
*erstellt durch GUI; ein Dokument wurde dem Nutzer angezeigt; published in Topic: <code>Constants.PubSub.Topic.FEEDBACK_GUI</code>*
#### Attribute
<ul><li><code>userId: String</code></li><li><code>documentId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.FEEDBACK</code></li></ul>

## SuccessfullFeedbackEvent
*erstellt durch GUI; ein Dokument wurde vom Nutzer angeklickt; published in Topic: <code>Constants.PubSub.Topic.FEEDBACK_GUI</code>*
#### Attribute
<ul><li><code>userId: String</code></li><li><code>documentId: String</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.USER_INTERFACE</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.SUCCESSFULL_FEEDBACK</code></li></ul>

**Comment by WendelinHerrmann** [comment]
Also mir fehlen ehrlich gesagt einige Events, von denen wir bisher ausgegangen waren und die wir auch Mittwoch abgesprochen haben:

- neue Session erstellt (wird ausgelöst, wenn ein User über die enstprechende Funktion eine neue Session erstellt - das ist glaube ich euer SessionStartEvent, dann ist da aber die Beschreibung falsch, da die Beschreibung ein UserJoinedSessionEvent wäre)
- Anlegen neuer Zusatzinformationen (es wurde erkannt, dass der sich einloggende User dem System nicht bekannt ist (Erkenntnis-Event der SemRep, gibt's das?) woraufhin wir Zusatzinformationen abfragen und über ein Event übermitteln)
- User startet die Recommender-Funktion (der User muss die Aufnahme und Vorschlagsanzeige bewusst starten, auch wenn er zuvor der Session schon beigetreten ist - man könnte höchstens überlegen, ob ein User erst dann als "JoinedSession" gemeldet wird, wenn er hier startet)
- Rückmeldung, dass ein Vorschlag verarbeitet und angezeigt wurde

Was wir bisher nicht auf dem Schirm haben und in eurer Liste neu ist, ist das "UserLogoutEvent", da wir hierfür bis jetzt keinen Nutzen gesehen haben, da zuvor stets eine SessionLeft stattfindet, was systemseitig alles beenden sollte. Braucht man den zusätzlichen Logout?

**Comment by ChristianSchn** [comment]
> neue Session erstellt
- Beschreibung von SessionStartEvent angepasst

> Anlegen neuer Zusatzinformationen
- in Klärung mit SemRep, habt ihr dann ein Formular das alle User-Daten abfragt? Vielleicht unnötig komplex.

> User startet die Recommender-Funktion
- hinzugefügt als UserStartEvent

> Rückmeldung, dass ein Vorschlag verarbeitet und angezeigt wurde
- angepasst; FeedbackEvent=Vorschlag angezeigt; SuccessfulFeedbackEvent=Vorschlag angeklickt

- UserLogoutEvent gelöscht; wurde zur Vollständigkeit hinzugefügt, erfüllt aber tatsächlich keinen Zweck.

**Comment by Mag91** [comment]
habe gerade von bene erfahren, dass messages auch events sind. und wir die deshalb ebenfalls benennen sollen. 
Dummydaten, wie die Vorschläge später aussehen sind im server unter: 
https://github.com/Purii/hdm-wim-devlab/blob/master/GUI/js/server.js  ab Zeile 45 zu finden. 

Bisher läuft es so ab, dass der server und alle Clients auf den selben port hören. die Clients entscheiden dann anhand der id (://localhost/cloud/GUI_FINAL/php/meetingraum3.php?&**id=1**) am ende der URL ob der Vorschlag { **'SessionID':'1',**'TimeStamp':timeInMs, 'DokumentenID': '098765', 'name':'Dokument1', 'prio':1, 'DokuTyp':'gdoc', 'link': 'https://docs.google.com/document/d/1bkLCvEBX56OBrECe89SFxpaqhlfQfZtOUNHNxM2Rlmc/edit', 'folder': 'Mercedesprojekt' } zu ihnen passt und angezeigt wird oder nicht.

**Comment by DimadonDL** [comment]
Kurze Frage zum Event: SuccessfullFeedbackEvent

Hier fehlt mir das Feedback: true 

@WendelinHerrmann @Mag91 @ChristianSchn

**Comment by DimadonDL** [comment]
SuccessfullFeedbackEvent

Hallo Kollegen @Mag91 @WendelinHerrmann @ChristianSchn ,

da dieses Event ja wahrscheinlich nur uns betrifft nochmal eine klare Definition:

Wir brauchen die Attributnamen:

SuccessfullFeedbackEvent

userId: String
documentId: String
documentAffiliation: String --> immer true da kein negatives Feedback kommt.

Wirklich wichtig ist, die exakte Benennung der Attribute wie oben beschrieben!!! Bitte hierauf achten. Wenn es Probleme hierbei gibt bitte Rücksprache vor der finalen Präsi.

**Comment by ChristianSchn** [comment]
Hey Dani,

is genau so vorgesehen. Die Konstanten sehen so aus:

public static final String USER_ID		= "userId";
public static final String DOCUMENT_ID	= "documentId";
public static final String DOCUMENT_AFFILIATION	= "documentAffiliation";

Einzusehen in der [Konstantenklasse](https://github.com/Purii/hdm-wim-devlab/blob/master/sharedLib/src/main/java/de/hdm/wim/sharedLib/Constants.java)

**Comment by WendelinHerrmann** [comment]
@ChristianSchn 

das Zusatzinformationen speichern Event fehlt immer noch. Laut @Mag91 ist es mit SemRep so abgesprochen, dass wir den User per Dropdown abfragen, welche Zuordnungen er hat in den Kategorien und das ganze dann als Event zurückschicken, dass es SemRep speichern kann

Attribute wären hierfür denke ich: UserID, Antwort auf Kategorie 1, Antwort auf Kategorie 2, Antwort auf Kategorie 3 und Antwort auf Kategorie 4 denke ich. Wären alles Strings

**Comment by ChristianSchn** [comment]
AdditionalUserInformationEvent

@Mag91 
gibts da einen Beispielaufbau? Da wir mit Konstanten arbeiten, können wir statt Kategorie 1-4 nicht richtige Bezeichner nehmen (z.B. userBelongsToCompany)?
