### ISSUE TITLE
[SPEECH] Attribute aller Events festlegen

### ISSUE THREAD

**Issue by ChristianSchn** [Purii/hdm-wim-devlab#29]
# Hallo Speech Tokenizer

bitte ergänzt für alle aufgeführten Events die Attribute durch Edit. Die Schreibweise ist erstmal unwichtig, wir normieren die Attribute in der [Konstantenklasse](https://github.com/Purii/hdm-wim-devlab/blob/master/SharedLib/src/main/java/de/hdm/wim/sharedLib/Constants.java).  Falls Events fehlen, bitte um direkte Rückmeldung. Eine Liste aller Events inkl. Aufbau ist [hier](https://github.com/Purii/hdm-wim-devlab/blob/master/docs/Events.md) einzusehen.

## TokenEvent
*erstellt durch ST; beinhaltet den Token; published in Topic: <code>Constants.PubSub.Topic.TOKEN</code>*
<ul><li><code>sessionId: String</code></li>
<li><code>userId: String</code></li>
<li><code>timestamp: Int</code></li>
<li><code>contexts: Array</code></li>
<li><code>tokens: Array</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.SPEECH_TOKENIZATION</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.TOKEN</code></li></ul>

**Comment by ghost** [comment]
Hallo CEP,

haben unsere Attribute aktualisiert.

LG
Speech

**Comment by ghost** [comment]
Hi CEP,

könntet ihr bitte noch Inci Kökpinar (GITHUB: incim) hinzufügen? 
Sie hat immernoch keinen Zugriff.

Merci,
Speech

**Comment by Purii** [comment]
@na0mi, dann muss Inci auch die Einladung annehmen.
Habe sie nochmal hinzugefügt. Leider scheint eine Einladung bei GitHub relativ schnell abzulaufen, deshalb muss sie zeitnah auf folgenden Link klicken, um die Einladung anzunehmen:
https://github.com/Purii/hdm-wim-devlab/invitations

**Comment by Purii** [comment]
`kontexts`. Würde gerne im englischen bleiben. `contexts` in Ordnung?

**Comment by ghost** [comment]
Ja, passt 👍

**Comment by nilsbch** [comment]
Sind das jeweils arraylist<String> attribute für tokens und contexts?

**Comment by nilsbch** [comment]
arraylist string

**Comment by ghost** [comment]
ja, klar.
