### ISSUE TITLE
[MACHINE LEARNING] Attribute aller Events festlegen

### ISSUE THREAD

**Issue by ChristianSchn** [Purii/hdm-wim-devlab#30]
# Hallo Machine Learning

bitte ergänzt für alle aufgeführten Events die Attribute durch Edit. Die Schreibweise ist erstmal unwichtig, wir normieren die Attribute in der [Konstantenklasse](https://github.com/Purii/hdm-wim-devlab/blob/master/SharedLib/src/main/java/de/hdm/wim/sharedLib/Constants.java).  Falls Events fehlen, bitte um direkte Rückmeldung. Eine Liste aller Events inkl. Aufbau ist [hier](https://github.com/Purii/hdm-wim-devlab/blob/master/docs/Events.md) einzusehen.

## LearnEvent
*erstellt durch ML; Kontext zwischen Personen oder Dokumenten zu Projekten; published in Topic: <code>Constants.PubSub.Topic.INSIGHTS</code>*
#### Attribute
<ul><li><code>userId: String</code></li><li><code>documentId: String</code></li><li><code>projectId: String</code></li><li><code>documentAffiliation: Boolean (true)</code></li><li><code>constants.AttributeKey.EVENT_SOURCE: Constants.PubSub.EventSource.MACHINE_LEARNING</code></li><li><code>constants.AttributeKey.EVENT_TYPE: Constants.PubSub.EventType.LEARN</code></li></ul>

**Comment by DimadonDL** [comment]
Habe den Userclick noch hinzugefügt. Hier wird grundsätzlich eigentlich immer der Wert true hinzugefügt. Attributname ist jetzt nur von mir frei gewählt.

**Comment by DimadonDL** [comment]
Habe unsere Feedback nochmals angepasst. Bitte beachten. @bjoernZimmermann @ChristianSchn

**Comment by ChristianSchn** [comment]
Okay 👍
