### ISSUE TITLE
[Alle] Topics festlegen

### ISSUE THREAD

**Issue by itsBen** [Purii/hdm-wim-devlab#32]
Da wir der Kommunikation zwischen den Gruppen über PubSub immer näher kommen, müssen wir die Topics festlegen. D.h. Wer an welche Topic publisht und wer welche Topic empfängt.

Bisher laufen alle Gruppen auf `topic-1` zum testen.

Implementierung PubSub:
- SemRep
  - [x] Senden
  - [ ] Empfangen
- Speech
  - [x] Senden
  - [ ] Empfangen
- GUI
  - [x] Senden
  - [ ] Empfangen
- CEP
  - [x] Senden
  - [ ] Empfangen
- ML
  - [x] Senden
  - [x] Empfangen

**Comment by ChristianSchn** [comment]
Bitte kommentiert hierzu für alle für euch wichtigen Events (aktuelle Version [hier](https://github.com/Purii/hdm-wim-devlab/blob/master/docs/Events.md)). Welche Events publisht ihr (und für wen sind diese gedacht)? Welche Events subscribet ihr (und von wem stammen diese)?

**Comment by ChristianSchn** [comment]
**EVENT**

* publish

CEP -> SemRep: 
DocumentContextEvent 
DocumentHighlyRelevantEvent 
UserContextEvent 

CEP -> Speech/ML:
SessionEndEvent

CEP -> GUI:
UserInactiveEvent 

* subscribe

SemRep -> CEP:
DocumentInformationEvent
UserInformationEvent 

GUI -> CEP:
StayAliveEvent 
SuccessfulFeedbackEvent 
UserJoinedSessionEvent 
UserLeftSessionEvent

**Comment by ChristianSchn** [comment]
**Machine Learning**

* publish

ML -> SemRep:
LearnEvent

* subscribe

GUI -> ML:
SuccessFulFeedbackEvent

CEP -> ML:
SessionEndEvent

**Comment by ChristianSchn** [comment]
**Speech Tokenizer** (Vorschlag; bitte editieren)

* publish

ST -> SemRep:
TokenEvent

* subscribe

GUI-> ST:
SessionStartEvent

GUI -> ST:
SessionEndEvent

**Comment by ChristianSchn** [comment]
**GUI** (Vorschlag; bitte editieren)

* publish

GUI -> SemRep:
AdditionalUserInformationEvent
FeedbackEvent
UserLoginEvent
UserStartEvent

GUI -> ML, CEP, SemRep:
SuccessfulFeedbackEvent

GUI -> CEP, SemRep, ST:
SessionStartEvent

GUI -> CEP:
StayAliveEvent
UserJoinedSessionEvent
UserLeftSessionEvent

* subscribe

CEP -> GUI:
(SessionEndEvent)
UserInactiveEvent

SemRep -> GUI:
InformationToAllDocumentsEvent
OfferEvent
abgefragte Informationen (AllDepartmentsEvent, UserInformationEvent,...)

**Comment by ChristianSchn** [comment]
**SEMREP** (Vorschlag; bitte editieren)

* publish

SemRep -> CEP:
DocumentInformationEvent
UserInformationEvent  

SemRep -> GUI/alle:
AllCompaniesEvent
AllDepartmentsEvent
AllProjectsEvent 
AllProjectRolesEvent
DepartmentInformationEvent
ProjectInformationEvent

SemRep -> GUI:
InformationToAllDocumentsEvent
OfferEvent

* subscribe

GUI -> SemRep:
AdditionalUserInformationEvent
FeedbackEvent
SuccessFulFeedbackEvent
SessionStartEvent/UserStartEvent
UserLoginEvent

CEP -> SemRep:
(DocumentCallEvent)
DocumentHighlyRelevantEvent
DocumentContextEvent
UserContextEvent

ML -> SemRep:
LearnEvent

ST -> SemRep:
TokenEvent

**Comment by DimadonDL** [comment]
Passt von ML

**Comment by WendelinHerrmann** [comment]
Bei GUI hab ich paar Anmerkungen:

**Publish-Seite:**

- Das SessionStartEvent geht meiner Meinung nach neben CEP und SemRep auch an Speech für den Start des Protokolls, oder?
- Das UserLoginEvent fehlt bei uns komplett. Das geht aber an SemRep, da die uns daraufhin das UserInformationEvent schicken müssen
- Das UserStartEvent fehlt bei uns komplett. Das geht an SemRep wegen der Initialisierung der GUI und evtl. an Speech wegen Aufnahme ins Protokoll (da weiß ich aber nicht, wie das Protokoll aktuell funktioniert)

**Subscripe-Seite:**
Hab mir das ganze gerade, auch wegen Doku, nochmal angeschaut: eigentlich brauchen wir ja weder das SessionEndEvent noch das UserInactiveEvent. SessionEnd tritt nur ein, wenn alle unsere Clients dieser Session beendet sind, daher sind wir da ja eh schon nicht mehr existent im Bezug auf diese Session. UserInactive ist ziemlich ähnlich, da der Client den es betrifft ja weg ist und die anderen nichts von anderen Clients wissen, also diese Information auch nicht brauchen.
Was meint ihr dazu @Mag91 , @Florianmarkblessing und @ChristianSchn ? Hab ich nen Denkfehler oder passt das so?

**Comment by ChristianSchn** [comment]
**Publish**
Danke für die Info, hab ich hinzugefügt/geändert. Ich denk ST zeigt nur den Gesprächsverlauf.

**Subscribe**
SessionEndEvent ist für euch tatsächlich nicht nützlich, außer ihr würdet die Session offen halten bis wir das Signal auf Ende geben. Da habt ihr aber wohl andere Pläne. UserInactive braucht ihr, weil ein User ja vor Sessionende schon passiv ausgeloggt werden könnte.

**Comment by WendelinHerrmann** [comment]
Ja gerade auch aufgefallen, SessionEnd ist uns echt egal, aber UserInactive brauchen wir allein schon für die anzeige "aktive Teilnehmer" in den anderen Clients :) danke

**Comment by ghost** [comment]
Hi all,

haben unsere Events aktualisiert, benötigen noch einen Event, um den Link zum Doc Dokument zu hinterlegen.

Merci :D

**Comment by ChristianSchn** [comment]
Wie in Issue "ProtocolEvent wird benötigt #33" besprochen, kein neues Event.

**Comment by ChristianSchn** [comment]
Die zu verwendenden Topics sind jetzt final und liegen [hier](https://github.com/Purii/hdm-wim-devlab/blob/master/docs/Topics.md) ab!
@itsBen @LepiorzDaniel @WendelinHerrmann @na0mi @bjoernZimmermann
