### ISSUE TITLE
ProtocolEvent wird benötigt

### ISSUE THREAD

**Issue by ghost** [Purii/hdm-wim-devlab#33]
Hi CEP,

wir benötigen noch einen Event, damit wir den Link zum DriveDoc (Protokoll) veröffentlichen können.

Danke

LG
ST

**Comment by itsBen** [comment]
@ChristianSchn

**Comment by ChristianSchn** [comment]
ist mit der Gruppe geklärt:
ST erstellt das Protokoll nach dem SessionEndEvent und legt es in dem Ordner ab. Das Protokoll kann vom User nach dem Logout/Verlassen der Session im Drive-Ordner aufgerufen werden. Es erfolgt keine Anzeige in der Session.
