### ISSUE TITLE
Zugriff auf PubSub

### ISSUE THREAD

**Issue by DimadonDL** [Purii/hdm-wim-devlab#4]
Daniel.Lepiorz@gmail.com

**Comment by Purii** [comment]
mateos.alliaj@gmail.com

**Comment by itsBen** [comment]
Hab beide geadded

**Comment by ghost** [comment]
Bitten um Freischaltung

nermin.hasani@gmail.com
ekesicil@gmail.com
inci.koekpinar@gmail.com

Merci

**Comment by Florianmarkblessing** [comment]
florianmarkblessing@gmail.com

**Comment by Mag91** [comment]
markus.goetz91@gmail.com
