### ISSUE TITLE
[Alle] Komplexe Events identifizieren

### ISSUE THREAD

**Issue by Purii** [Purii/hdm-wim-devlab#6]
* [x] **Dokument vermutlich relevant** Event(Dokument angeboten) + Event(Dokument geklickt)
* [x] **Kontext identifizieren** Auch auf Basis von angeklickten Dokumenten (Semrep: Dokument gehört zu folgendem Projekt/Kontext --> Mehrere Vorschlage zu einem Projekt --> Event: Kontext ist "HighNet")
* [x] **Kontext identifizieren** auf Basis von Person (Verfasste Dokumente, Hat aufgerufen, Favorisiert, Projekt) arbeitet an --> Macht ML (@LepiorzDaniel @bjoernZimmermann)
* [x] **Kontext / Aktualität identifizieren** auf Basis des Erstelldaten vorgeschlagener Dokumente (--> GUI kann Button anbieten "neues Dokument anlegen")
* [x] **Kontext identifizieren** auf Basis der meist genutzten Keywords
--> Definition "Kontext" ("es geht gerade um Videokonferenz", "es geht gerade um Projekt HighNet",..)
* [x] **DocumentHighlyRelevantEvent** User klickt binnen weniger Sekunden mehrfach auf denselben Vorschlag

<hr/>

* [ ] **Favoriten des Users identifizieren** auf Basis der Feedbacks (User ruft gerne auf...) --> Aufgabe ML
* [x] **Sessionende / Gesprächsende identifizieren** (Abgleich mit angemeldeten Usern)
* [x] **Passiven Logout identifizieren** (GUI sendet Ping Event in definiertem Intervall)
* [ ] **Passiver Logout + !Sessionende + Aktiver Login** (GUI kann Wiedereinstieg anbieten)
* [ ] **Aktuelle Teilnehmer** wird ausgelöst nach jedem Login / Logout

<hr/>

* [ ] **`Google Calender` identifizieren**, um Vorschlagsevent zu generieren (Tokens werden in einem einzelnen Event gesendet: "appointment", "next meeting") --> Aufgabe Speech (Nutzer spricht von Google Calendar) -> GUI zeigt auf dieser Basis Link an
* [ ] **`Google Drive` identifizieren**, um Vorschlagsevent zu generieren --> Aufgabe Semantische Repräsentation (@bjoernZimmermann @mateos-alliaj) 

--
**Komplexes Event:** Identifizierung von Pattern beim auftreten von Events.

**An alle:** Bitte ergänzen, welche komplexen Events für Eure Gruppe relevant sein kann. Einfach kommentieren. Ich aktualisiere dann die Liste.

**Comment by mateos-alliaj** [comment]
### Beispiel für RichToken

```
Person: Person=Kristjan_Alliaj, ID=2, Klasse=Externer_Mitarbeiter, NamedIndividual, Vorname=Kristjan, Nachname=Alliaj, Mail=kristjan.alliaj@gmail.com, Person_arbeitet_an_Projekt=HighNet, Person_hat_Projektrolle=Entwickler, Person_gehoert_zu_Abteilung=IT, Person_hat_Dokument_verfasst=_Aufgabenliste_HighNet, Person_ruft_Dokument_auf=_KickOff_HighNet, _Aufgabenliste_HighNet, Person_favorisiert_Dokument=_KickOff_HighNet
```

```
Dokument_1: Dokument_1=_Meilensteine_HighNet, Klasse=NamedIndividual, Dokument, Dok_Name=Meilensteine, Dok_ID=1jQFZmcS__-CtScjqd3g5KKM8xepPnMSqaepy2ag2jNc, Dok_URL=https://docs.google.com/document/d/1jQFZmcS__-CtScjqd3g5KKM8xepPnMSqaepy2ag2jNc/edit, Dok_Erstelldatum=2017-04-28T11:59:00, Dok_Updatedatum=2017-05-01T09:34:00, Dok_Version=1.1, Dok_Typ=Google Docs, Dokument_verfasst_von_Person=Mateos_Alliaj, Lisa_Meier, Haruki_Murakami, Kristjan_Alliaj, Björn_Zimmermann, Donald_Trump, Ivan_Kurtovic, Dokument_gehoert_zu_Phase=Definition, Dokument_hat_Dokumentenkategorie=Planungen, Textdokumente, Praesentationen, Tabellen, Dokument_gehoert_zu_Projekt=HighNet, BlackWater, Dokument_favorisiert_von_Person=Haruki_Murakami, Donald_Trump, Kristjan_Alliaj, Mateos_Alliaj, Lisa_Meier, Björn_Zimmermann, Ivan_Kurtovic, Dok_Keywords=milestone, kickoff-HighNet, kickoff, project_plan, project_planning, planning, to-do_list, tasks, list, listing, costs, cost_planning, report, financial_report, finances, Kontext=activities_concerning_the_HighNet_project, activities_concerning_the_BlackWater_project
```

**Comment by WendelinHerrmann** [comment]
Es fehlt 
**Session beendet:** letzter Nutzer hat Session verlassen

**Comment by Purii** [comment]
Der Login wird vollständig über eine Schnittstelle von Google realisiert. Hier können also keine komplexen Events abgeleitet werden, wie beispielsweise fehlgeschlagene Loginversuche.

**Comment by ChristianSchn** [comment]
Warum `Google Calender` und `Google Drive`?
